// TerraAuth — 服务端权威伤害结算：武器基础伤害表（阶段 E 全量补齐）
// 阶段 E：近战与无固定弹幕映射的魔法命中按**手持武器权威伤害**校验包 28 上报值；
//          有固定弹幕映射的魔法命中还必须关联服务端登记且实际接触目标的自有弹幕。
// 阶段 F：远程命中按**武器 + 弹药**权威伤害校验（弹幕伤害 = 武器 + 弹药，原版 PickAmmo 合并，
//         弹药乘修饰倍率，见 WeaponAmmoTypeOf / AmmoTypeOf / CombatResolver.RangedDamageBound）；
//         无弹药合并的远程（投掷 / 鱼叉 / gunProj 四件）按武器伤害校验。召唤仆从伤害 ≠ 手持武器，失败放行。
//          本表仍收录召唤武器作为权威数据，但不参与武器上界校验。
// 数据源：Terraria 1.4.5.8 原版 Item.SetDefaults1-5 的 damage 字段（取 **case 内基础赋值**，
//          排除 StrongerVariant 等变体 if 块内的覆盖；ID 以 ItemID.cs 为准）。
// 未收录的物品（含空手 / 未知武器 / 弹药 / 工具）→ 失败放行（退回既有上限校验），绝不误拒。
// 注意：1.4.5.8 铜/锡/银/金系列在 3500+（变体 switch），3500=锡斧、3504=铜弓（无「锡弓」）；
//       367=肉山锤、204=陨石锤斧、2750=陨星法杖；悠悠球 3278-3285 为变体实现。

using System.Collections.Generic;

namespace TerraAuth.Simulation;

/// <summary>武器条目：基础伤害 + 职业（决定 buff/套装修饰列与是否参与武器上界校验）。</summary>
public readonly record struct WeaponStats(int Damage, WeaponClass Class);

/// <summary>
/// 物品 ID → 武器基础伤害（原版 <c>Item.damage</c>，不含任何修饰）。
/// 覆盖原版 1.4.5.8 全部近战 / 魔法武器及常见远程 / 召唤武器。
/// </summary>
public static class ItemDamageTable
{
    public static readonly IReadOnlyDictionary<int, WeaponStats> Of = new Dictionary<int, WeaponStats>
    {
        // ---- 近战：工具（镐/斧/锤，挥砍同样伤怪）----
        [1]   = new(5,  WeaponClass.Melee),   // IronPickaxe
        [10]  = new(5,  WeaponClass.Melee),   // IronAxe
        [7]   = new(7,  WeaponClass.Melee),   // IronHammer
        [196] = new(2,  WeaponClass.Melee),   // WoodenHammer
        // ---- 前困难模式金属武器（1.4.5.8 的 3480-3499 段，3500+ 变体 switch 的前身）----
        [3480] = new(13, WeaponClass.Ranged),  // 铂金弓 Platinum Bow
        [3481] = new(10, WeaponClass.Melee),   // 铂金锤 Platinum Hammer
        [3482] = new(8,  WeaponClass.Melee),   // 铂金斧 Platinum Axe
        [3483] = new(13, WeaponClass.Melee),   // 铂金短剑 Platinum Shortsword
        [3484] = new(16, WeaponClass.Melee),   // 铂金阔剑 Platinum Broadsword
        [3485] = new(7,  WeaponClass.Melee),   // 铂金镐 Platinum Pickaxe
        [3486] = new(10, WeaponClass.Ranged),  // 钨弓 Tungsten Bow
        [3487] = new(9,  WeaponClass.Melee),   // 钨锤 Tungsten Hammer
        [3488] = new(7,  WeaponClass.Melee),   // 钨斧 Tungsten Axe
        [3489] = new(10, WeaponClass.Melee),   // 钨短剑 Tungsten Shortsword
        [3490] = new(14, WeaponClass.Melee),   // 钨阔剑 Tungsten Broadsword
        [3491] = new(6,  WeaponClass.Melee),   // 钨镐 Tungsten Pickaxe
        [3492] = new(9,  WeaponClass.Ranged),  // 铅弓 Lead Bow
        [3493] = new(8,  WeaponClass.Melee),   // 铅锤 Lead Hammer
        [3494] = new(6,  WeaponClass.Melee),   // 铅斧 Lead Axe
        [3495] = new(9,  WeaponClass.Melee),   // 铅短剑 Lead Shortsword
        [3496] = new(13, WeaponClass.Melee),   // 铅阔剑 Lead Broadsword
        [3497] = new(6,  WeaponClass.Melee),   // 铅镐 Lead Pickaxe
        [3498] = new(7,  WeaponClass.Ranged),  // 锡弓 Tin Bow
        [3499] = new(6,  WeaponClass.Melee),   // 锡锤 Tin Hammer
        [3500] = new(4,  WeaponClass.Melee),  // 锡斧 Tin Axe
        [3503] = new(5,  WeaponClass.Melee),  // 锡镐 Tin Pickaxe
        [3505] = new(4,  WeaponClass.Melee),  // 铜锤 Copper Hammer
        [3506] = new(3,  WeaponClass.Melee),  // 铜斧 Copper Axe
        [3509] = new(4,  WeaponClass.Melee),  // 铜镐 Copper Pickaxe
        [3511] = new(9,  WeaponClass.Melee),  // 银锤 Silver Hammer
        [3512] = new(6,  WeaponClass.Melee),  // 银斧 Silver Axe
        [3515] = new(6,  WeaponClass.Melee),  // 银镐 Silver Pickaxe
        [3517] = new(9,  WeaponClass.Melee),  // 金锤 Gold Hammer
        [3518] = new(7,  WeaponClass.Melee),  // 金斧 Gold Axe
        [3521] = new(6,  WeaponClass.Melee),  // 金镐 Gold Pickaxe
        [103] = new(9,  WeaponClass.Melee),   // NightmarePickaxe
        [122] = new(12, WeaponClass.Melee),   // MoltenPickaxe
        [1320] = new(8,  WeaponClass.Melee),  // BonePickaxe
        [204] = new(20, WeaponClass.Melee),   // MeteorHamaxe
        [217] = new(20, WeaponClass.Melee),   // MoltenHamaxe
        [367] = new(26, WeaponClass.Melee),   // Pwnhammer
        [213] = new(7,  WeaponClass.Melee),   // StaffofRegrowth
        [383] = new(23, WeaponClass.Melee),   // CobaltChainsaw
        [384] = new(29, WeaponClass.Melee),   // MythrilChainsaw
        [385] = new(10, WeaponClass.Melee),   // CobaltDrill
        [386] = new(15, WeaponClass.Melee),   // MythrilDrill
        [387] = new(33, WeaponClass.Melee),   // AdamantiteChainsaw
        [388] = new(20, WeaponClass.Melee),   // AdamantiteDrill
        [579] = new(35, WeaponClass.Melee),   // Drax
        [654] = new(7,  WeaponClass.Melee),   // EbonwoodHammer
        [657] = new(4,  WeaponClass.Melee),   // RichMahoganyHammer
        [660] = new(10, WeaponClass.Melee),   // PearlwoodHammer
        [776] = new(10, WeaponClass.Melee),   // CobaltPickaxe
        [777] = new(15, WeaponClass.Melee),   // MythrilPickaxe
        [778] = new(20, WeaponClass.Melee),   // AdamantitePickaxe
        [787] = new(26, WeaponClass.Melee),   // Hammush
        [798] = new(12, WeaponClass.Melee),   // DeathbringerPickaxe
        [882] = new(4,  WeaponClass.Melee),   // CactusPickaxe
        [922] = new(7,  WeaponClass.Melee),   // ShadewoodHammer
        [990] = new(35, WeaponClass.Melee),   // PickaxeAxe
        [991] = new(33, WeaponClass.Melee),   // CobaltWaraxe
        [992] = new(39, WeaponClass.Melee),   // MythrilWaraxe
        [993] = new(43, WeaponClass.Melee),   // AdamantiteWaraxe
        [1188] = new(12, WeaponClass.Melee),  // PalladiumPickaxe
        [1189] = new(12, WeaponClass.Melee),  // PalladiumDrill
        [1190] = new(26, WeaponClass.Melee),  // PalladiumChainsaw
        [1195] = new(17, WeaponClass.Melee),  // OrichalcumPickaxe
        [1196] = new(17, WeaponClass.Melee),  // OrichalcumDrill
        [1197] = new(31, WeaponClass.Melee),  // OrichalcumChainsaw
        [1202] = new(27, WeaponClass.Melee),  // TitaniumPickaxe
        [1203] = new(27, WeaponClass.Melee),  // TitaniumDrill
        [1204] = new(34, WeaponClass.Melee),  // TitaniumChainsaw
        [1222] = new(36, WeaponClass.Melee),  // PalladiumWaraxe
        [1223] = new(41, WeaponClass.Melee),  // OrichalcumWaraxe
        [1224] = new(44, WeaponClass.Melee),  // TitaniumWaraxe
        [1230] = new(40, WeaponClass.Melee),  // ChlorophytePickaxe
        [1231] = new(35, WeaponClass.Melee),  // ChlorophyteDrill
        [1232] = new(50, WeaponClass.Melee),  // ChlorophyteChainsaw
        [1233] = new(70, WeaponClass.Melee),  // ChlorophyteGreataxe
        [1234] = new(80, WeaponClass.Melee),  // ChlorophyteWarhammer
        [1262] = new(45, WeaponClass.Melee),  // ChlorophyteJackhammer
        [1294] = new(34, WeaponClass.Melee),  // Picksaw
        [1325] = new(12, WeaponClass.Melee),  // ChainKnife
        [1506] = new(32, WeaponClass.Melee),  // SpectrePickaxe
        [1507] = new(60, WeaponClass.Melee),  // SpectreHamaxe
        [1917] = new(7,  WeaponClass.Melee),  // CnadyCanePickaxe
        [2176] = new(45, WeaponClass.Melee),  // ShroomiteDiggingClaw
        [3098] = new(120, WeaponClass.Melee), // ButchersChainsaw
        [3772] = new(16, WeaponClass.Melee),  // AntlionClaw
        [5095] = new(27, WeaponClass.Melee),  // LucyTheAxe
        [5295] = new(20, WeaponClass.Melee),  // AcornAxe
        // ---- 近战：剑 ----
        [24]  = new(7,  WeaponClass.Melee),   // WoodenSword
        [3507] = new(5,  WeaponClass.Melee),  // 铜短剑 Copper Shortsword
        [3508] = new(9,  WeaponClass.Melee),  // 铜阔剑 Copper Broadsword
        [3501] = new(7,  WeaponClass.Melee),  // 锡短剑 Tin Shortsword
        [3502] = new(10, WeaponClass.Melee),  // 锡阔剑 Tin Broadsword
        [6]   = new(8,  WeaponClass.Melee),   // IronShortsword
        [4]   = new(12, WeaponClass.Melee),   // IronBroadsword
        [3513] = new(9,  WeaponClass.Melee),  // 银短剑 Silver Shortsword
        [3514] = new(14, WeaponClass.Melee),  // 银阔剑 Silver Broadsword
        [3519] = new(12, WeaponClass.Melee),  // 金短剑 Gold Shortsword
        [3520] = new(15, WeaponClass.Melee),  // 金阔剑 Gold Broadsword
        [881] = new(10, WeaponClass.Melee),   // CactusSword
        [653] = new(11, WeaponClass.Melee),   // EbonwoodSword
        [656] = new(8,  WeaponClass.Melee),   // RichMahoganySword
        [921] = new(11, WeaponClass.Melee),   // ShadewoodSword
        [659] = new(30, WeaponClass.Melee),   // PearlwoodSword
        [946] = new(10, WeaponClass.Melee),   // Umbrella
        [45]  = new(20, WeaponClass.Melee),   // WarAxeoftheNight
        [46]  = new(16, WeaponClass.Melee),   // LightsBane
        [795] = new(22, WeaponClass.Melee),   // BloodButcherer
        [989] = new(23, WeaponClass.Melee),   // EnchantedSword
        [1304] = new(15, WeaponClass.Melee),  // ZombieArm
        [724] = new(17, WeaponClass.Melee),   // IceBlade
        [186] = new(10, WeaponClass.Melee),   // BreathingReed
        [190] = new(18, WeaponClass.Melee),   // BladeofGrass
        [65]  = new(25, WeaponClass.Melee),   // Starfury
        [104] = new(24, WeaponClass.Melee),   // TheBreaker
        [121] = new(40, WeaponClass.Melee),   // FieryGreatsword
        [155] = new(24, WeaponClass.Melee),   // Muramasa
        [1123] = new(30, WeaponClass.Melee),  // BeeKeeper
        [1166] = new(19, WeaponClass.Melee),  // BoneSword
        [3368] = new(25, WeaponClass.Melee),  // Arkhalis
        [273] = new(40, WeaponClass.Melee),   // NightsEdge
        [198] = new(26, WeaponClass.Melee),   // BluePhaseblade
        [199] = new(26, WeaponClass.Melee),   // RedPhaseblade
        [200] = new(26, WeaponClass.Melee),   // GreenPhaseblade
        [201] = new(26, WeaponClass.Melee),   // PurplePhaseblade
        [202] = new(26, WeaponClass.Melee),   // WhitePhaseblade
        [203] = new(26, WeaponClass.Melee),   // YellowPhaseblade
        [4258] = new(26, WeaponClass.Melee),  // OrangePhaseblade
        [5535] = new(26, WeaponClass.Melee),  // PinkPhaseblade
        [5670] = new(26, WeaponClass.Melee),  // RainbowPhaseblade
        [3764] = new(50, WeaponClass.Melee),  // Phasesaber (Blue)
        [3765] = new(50, WeaponClass.Melee),  // Phasesaber (Red)
        [3766] = new(50, WeaponClass.Melee),  // Phasesaber (Green)
        [3767] = new(50, WeaponClass.Melee),  // Phasesaber (Purple)
        [3768] = new(50, WeaponClass.Melee),  // Phasesaber (White)
        [3769] = new(50, WeaponClass.Melee),  // YellowPhasesaber
        [4259] = new(50, WeaponClass.Melee),  // OrangePhasesaber
        [5536] = new(50, WeaponClass.Melee),  // PinkPhasesaber
        [5671] = new(50, WeaponClass.Melee),  // RainbowPhasesaber
        [3525] = new(60, WeaponClass.Melee),  // LunarHamaxe (Stardust)
        [368] = new(72, WeaponClass.Melee),   // Excalibur
        [389] = new(50, WeaponClass.Melee),   // DaoofPow
        [426] = new(70, WeaponClass.Melee),   // BreakerBlade
        [482] = new(61, WeaponClass.Melee),   // AdamantiteSword
        [483] = new(40, WeaponClass.Melee),   // CobaltSword
        [484] = new(50, WeaponClass.Melee),   // MythrilSword
        [486] = new(12, WeaponClass.Melee),   // Ruler
        [671] = new(105, WeaponClass.Melee),  // Keybrand
        [672] = new(53, WeaponClass.Melee),   // Cutlass
        [674] = new(72, WeaponClass.Melee),   // TrueExcalibur
        [675] = new(70, WeaponClass.Melee),   // TrueNightsEdge
        [676] = new(49, WeaponClass.Melee),   // Frostbrand
        [723] = new(52, WeaponClass.Melee),   // BeamSword
        [757] = new(85, WeaponClass.Melee),   // TerraBlade
        [797] = new(23, WeaponClass.Melee),   // FleshGrinder
        [799] = new(22, WeaponClass.Melee),   // BloodLustCluster
        [1185] = new(49, WeaponClass.Melee),  // PalladiumSword
        [1192] = new(59, WeaponClass.Melee),  // OrichalcumSword
        [1199] = new(61, WeaponClass.Melee),  // TitaniumSword
        [1226] = new(95, WeaponClass.Melee),  // ChlorophyteClaymore
        [1227] = new(80, WeaponClass.Melee),  // ChlorophyteSaber
        [1297] = new(90, WeaponClass.Melee),  // GolemFist
        [1305] = new(72, WeaponClass.Melee),  // TheAxe
        [1306] = new(50, WeaponClass.Melee),  // IceSickle
        [1569] = new(29, WeaponClass.Melee),  // VampireKnives
        [1571] = new(70, WeaponClass.Melee),  // ScourgeoftheCorruptor
        [1825] = new(20, WeaponClass.Melee),  // BloodyMachete
        [1826] = new(150, WeaponClass.Melee), // TheHorsemansBlade
        [1827] = new(14, WeaponClass.Melee),  // BladedGlove
        [1909] = new(19, WeaponClass.Melee),  // CandyCaneSword
        [1928] = new(86, WeaponClass.Melee),  // ChristmasTreeSword
        [1947] = new(80, WeaponClass.Melee),  // NorthPole
        [3013] = new(60, WeaponClass.Melee),  // FetidBaghnakhs
        [3018] = new(50, WeaponClass.Melee),  // Seedler
        [3030] = new(40, WeaponClass.Melee),  // FlyingKnife
        [3054] = new(43, WeaponClass.Melee),  // ShadowFlameKnife
        [3063] = new(200, WeaponClass.Melee), // Meowmere
        [3065] = new(170, WeaponClass.Melee), // StarWrath
        [3106] = new(85, WeaponClass.Melee),  // PsychoKnife
        [3211] = new(55, WeaponClass.Melee),  // Bladetongue
        [3258] = new(55, WeaponClass.Melee),  // SlapHand
        [3473] = new(105, WeaponClass.Melee), // SolarEruption
        [3543] = new(150, WeaponClass.Melee), // DayBreak
        [3823] = new(95, WeaponClass.Melee),  // DD2SquireDemonSword
        [3827] = new(180, WeaponClass.Melee), // DD2SquireBetsySword
        [4144] = new(17, WeaponClass.Melee),  // Terragrim
        [4463] = new(15, WeaponClass.Melee),  // Gladius
        [4707] = new(15, WeaponClass.Melee),  // TragicUmbrella
        [4711] = new(12, WeaponClass.Melee),  // GravediggerShovel
        [4722] = new(190, WeaponClass.Melee), // FirstFractal
        [4760] = new(80, WeaponClass.Melee),  // BouncingShield
        [4923] = new(80, WeaponClass.Melee),  // PiercingStarlight
        [4956] = new(190, WeaponClass.Melee), // Zenith
        [5094] = new(20, WeaponClass.Melee),  // TentacleSpike
        [5096] = new(57, WeaponClass.Melee),  // HamBat
        [5097] = new(36, WeaponClass.Melee),  // BatBat
        [5284] = new(13, WeaponClass.Melee),  // AshWoodSword
        [5382] = new(50, WeaponClass.Melee),  // WaffleIron
        [5462] = new(70, WeaponClass.Melee),  // DeadCellsFlint
        [5669] = new(190, WeaponClass.Melee), // TrueCopperShortsword
        // ---- 近战：矛 / 链锤 / 回旋镖 / 悠悠球 ----
        [280] = new(8,  WeaponClass.Melee),   // Spear
        [277] = new(14, WeaponClass.Melee),   // Trident
        [274] = new(34, WeaponClass.Melee),   // DarkLance
        [162] = new(15, WeaponClass.Melee),   // BallOHurt
        [163] = new(27, WeaponClass.Melee),   // BlueMoon
        [220] = new(32, WeaponClass.Melee),   // Sunfury
        [284] = new(10, WeaponClass.Melee),   // WoodenBoomerang
        [55]  = new(17, WeaponClass.Melee),   // EnchantedBoomerang
        [191] = new(25, WeaponClass.Melee),   // ThornChakram
        [119] = new(49, WeaponClass.Melee),   // Flamarang
        [670] = new(21, WeaponClass.Melee),   // IceBoomerang
        [390] = new(45, WeaponClass.Melee),   // MythrilHalberd
        [406] = new(49, WeaponClass.Melee),   // AdamantiteGlaive
        [537] = new(44, WeaponClass.Melee),   // CobaltNaginata
        [550] = new(61, WeaponClass.Melee),   // Gungnir
        [561] = new(60, WeaponClass.Melee),   // LightDisc
        [756] = new(60, WeaponClass.Melee),   // MushroomSpear
        [801] = new(17, WeaponClass.Melee),   // TheMeatball
        [802] = new(17, WeaponClass.Melee),   // TheRottedFork
        [1122] = new(80, WeaponClass.Melee),  // PossessedHatchet
        [1186] = new(44, WeaponClass.Melee),  // PalladiumPike
        [1193] = new(46, WeaponClass.Melee),  // OrichalcumHalberd
        [1200] = new(48, WeaponClass.Melee),  // TitaniumTrident
        [1228] = new(49, WeaponClass.Melee),  // ChlorophytePartisan
        [1259] = new(65, WeaponClass.Melee),  // FlowerPow
        [1314] = new(40, WeaponClass.Melee),  // KOCannon
        [1324] = new(45, WeaponClass.Melee),  // Bananarang
        [1327] = new(57, WeaponClass.Melee),  // DeathSickle
        [1513] = new(100, WeaponClass.Melee), // PaladinsHammer
        [1786] = new(9,  WeaponClass.Melee),  // Sickle
        [1918] = new(19, WeaponClass.Melee),  // FruitcakeChakram
        [3012] = new(59, WeaponClass.Melee),  // ChainGuillotines
        [3097] = new(30, WeaponClass.Melee),  // EoCShield
        [3389] = new(190, WeaponClass.Melee), // Terrarian
        [3835] = new(50, WeaponClass.Melee),  // MonkStaffT1
        [3836] = new(45, WeaponClass.Melee),  // MonkStaffT2
        [3858] = new(140, WeaponClass.Melee), // MonkStaffT3
        [4272] = new(55, WeaponClass.Melee),  // DripplerFlail
        [4764] = new(23, WeaponClass.Melee),  // Shroomerang
        [4818] = new(25, WeaponClass.Melee),  // CombatWrench
        [5012] = new(9,  WeaponClass.Melee),  // FlamingMace
        [5294] = new(24, WeaponClass.Melee),  // HiveFive
        [5298] = new(21, WeaponClass.Melee),  // Trimarang
        [5519] = new(20, WeaponClass.Melee),  // Axearang
        [5526] = new(66, WeaponClass.Melee),  // FlaironFlail
        [5687] = new(12, WeaponClass.Melee),  // SlimeSpear
        [3278] = new(9,  WeaponClass.Melee),  // 木悠悠球 Wood Yoyo
        [3285] = new(14, WeaponClass.Melee),  // 拉力 Rally
        [3279] = new(16, WeaponClass.Melee),  // 腐化悠悠球 Corrupt Yoyo
        [3280] = new(17, WeaponClass.Melee),  // 猩红悠悠球 Crimson Yoyo
        [3281] = new(18, WeaponClass.Melee),  // 丛林悠悠球 Jungle Yoyo
        [3282] = new(27, WeaponClass.Melee),  // 瀑布 Cascade
        [3283] = new(34, WeaponClass.Melee),  // 木槿 Chik
        [3284] = new(54, WeaponClass.Melee),  // 代码 2 Code 2
        // ---- 魔法（无弹药合并，弹幕伤害 = 法杖伤害，可安全校验）----
        [64]  = new(10, WeaponClass.Magic),   // Vilethorn
        [112] = new(48, WeaponClass.Magic),   // FlowerofFire
        [113] = new(35, WeaponClass.Magic),   // MagicMissile
        [127] = new(20, WeaponClass.Magic),   // SpaceGun
        [157] = new(27, WeaponClass.Magic),   // AquaScepter
        [165] = new(19, WeaponClass.Magic),   // WaterBolt
        [218] = new(32, WeaponClass.Magic),   // Flamelash
        [272] = new(35, WeaponClass.Magic),   // DemonScythe
        [3069] = new(14, WeaponClass.Magic),  // WandofSparking
        [739] = new(15, WeaponClass.Magic),   // AmethystStaff
        [740] = new(16, WeaponClass.Magic),   // TopazStaff
        [741] = new(18, WeaponClass.Magic),   // SapphireStaff
        [742] = new(19, WeaponClass.Magic),   // EmeraldStaff
        [743] = new(18, WeaponClass.Magic),   // RubyStaff
        [744] = new(23, WeaponClass.Magic),   // DiamondStaff
        [788] = new(35, WeaponClass.Magic),   // NettleBurst
        [1121] = new(9,  WeaponClass.Magic),  // BeeGun
        [1256] = new(12, WeaponClass.Magic),  // CrimsonRod
        [1244] = new(30, WeaponClass.Magic),  // NimbusRod
        [2750] = new(50, WeaponClass.Magic),  // 陨星法杖 Meteor Staff
        [494] = new(42, WeaponClass.Magic),   // MagicalHarp
        [495] = new(50, WeaponClass.Magic),   // RainbowRod
        [496] = new(28, WeaponClass.Magic),   // IceRod
        [514] = new(29, WeaponClass.Magic),   // LaserRifle
        [517] = new(30, WeaponClass.Magic),   // MagicDagger
        [518] = new(35, WeaponClass.Magic),   // CrystalStorm
        [519] = new(55, WeaponClass.Magic),   // CursedFlames
        [683] = new(150, WeaponClass.Magic),  // UnholyTrident
        [726] = new(46, WeaponClass.Magic),   // FrostStaff
        [1155] = new(31, WeaponClass.Magic),  // WaspGun
        [1178] = new(48, WeaponClass.Magic),  // LeafBlower
        [1260] = new(45, WeaponClass.Magic),  // RainbowGun
        [1264] = new(60, WeaponClass.Magic),  // FlowerofFrost
        [1266] = new(48, WeaponClass.Magic),  // MagnetSphere
        [1295] = new(90, WeaponClass.Magic),  // HeatRay
        [1296] = new(125, WeaponClass.Magic), // StaffofEarth
        [1308] = new(43, WeaponClass.Magic),  // PoisonStaff
        [1313] = new(29, WeaponClass.Magic),  // BookofSkulls
        [1336] = new(30, WeaponClass.Magic),  // GoldenShower
        [1444] = new(80, WeaponClass.Magic),  // ShadowbeamStaff
        [1445] = new(70, WeaponClass.Magic),  // InfernoFork
        [1446] = new(65, WeaponClass.Magic),  // SpectreStaff
        [1801] = new(45, WeaponClass.Magic),  // BatScepter
        [1930] = new(48, WeaponClass.Magic),  // Razorpine
        [1931] = new(58, WeaponClass.Magic),  // BlizzardStaff
        [2188] = new(44, WeaponClass.Magic),  // VenomStaff
        [3006] = new(35, WeaponClass.Magic),  // SoulDrain
        [3014] = new(43, WeaponClass.Magic),  // ClingerStaff
        [3051] = new(25, WeaponClass.Magic),  // CrystalVileShard
        [3053] = new(32, WeaponClass.Magic),  // ShadowFlameHexDoll
        [3105] = new(52, WeaponClass.Magic),  // ToxicFlask
        [3209] = new(40, WeaponClass.Magic),  // CrystalSerpent
        [3269] = new(40, WeaponClass.Magic),  // MedusaHead
        [3377] = new(21, WeaponClass.Magic),  // AmberStaff
        [3476] = new(70, WeaponClass.Magic),  // NebulaArcanum
        [3541] = new(100, WeaponClass.Magic), // LastPrism
        [3542] = new(130, WeaponClass.Magic), // NebulaBlaze
        [3570] = new(100, WeaponClass.Magic), // LunarFlareBook
        [3779] = new(85, WeaponClass.Magic),  // SpiritFlame
        [3787] = new(38, WeaponClass.Magic),  // SkyFracture
        [3852] = new(36, WeaponClass.Magic),  // BookStaff
        [3870] = new(100, WeaponClass.Magic), // ApprenticeStaffT3
        [4270] = new(40, WeaponClass.Magic),  // SharpTears
        [4715] = new(85, WeaponClass.Magic),  // SparkleGuitar
        [4952] = new(50, WeaponClass.Magic),  // FairyQueenMagicItem
        [5118] = new(13, WeaponClass.Magic),  // WeatherPain
        [5147] = new(15, WeaponClass.Magic),  // WandofFrosting
        [5461] = new(22, WeaponClass.Magic),  // DeadCellsKillingDeck
        // ---- 远程（仅权威数据：弹药合并伤害无法按武器上界校验，E-5 起不参与武器校验）----
        [39]  = new(4,  WeaponClass.Ranged),  // WoodenBow
        [99]  = new(8,  WeaponClass.Ranged),  // IronBow
        [3504] = new(6,  WeaponClass.Ranged), // 铜弓 Copper Bow
        [3510] = new(9,  WeaponClass.Ranged), // 银弓 Silver Bow
        [3516] = new(11, WeaponClass.Ranged), // 金弓 Gold Bow
        [95]  = new(13, WeaponClass.Ranged),  // FlintlockPistol
        [96]  = new(31, WeaponClass.Ranged),  // Musket
        [98]  = new(6,  WeaponClass.Ranged),  // Minishark
        [279] = new(12, WeaponClass.Ranged),  // ThrowingKnife
        [281] = new(9,  WeaponClass.Ranged),  // Blowpipe
        [44]  = new(14, WeaponClass.Ranged),  // DemonBow
        [120] = new(31, WeaponClass.Ranged),  // MoltenFury
        [160] = new(25, WeaponClass.Ranged),  // Harpoon
        [164] = new(26, WeaponClass.Ranged),  // Handgun
        [197] = new(55, WeaponClass.Ranged),  // StarCannon
        [219] = new(30, WeaponClass.Ranged),  // PhoenixBlaster
        [266] = new(30, WeaponClass.Ranged),  // Sandgun
        [434] = new(17, WeaponClass.Ranged),  // ClockworkAssaultRifle
        [435] = new(35, WeaponClass.Ranged),  // CobaltRepeater
        [436] = new(39, WeaponClass.Ranged),  // MythrilRepeater
        [481] = new(42, WeaponClass.Ranged),  // AdamantiteRepeater
        [506] = new(35, WeaponClass.Ranged),  // Flamethrower
        [533] = new(25, WeaponClass.Ranged),  // Megashark
        [534] = new(24, WeaponClass.Ranged),  // Shotgun
        [578] = new(53, WeaponClass.Ranged),  // HallowedRepeater
        [655] = new(8,  WeaponClass.Ranged),  // EbonwoodBow
        [658] = new(6,  WeaponClass.Ranged),  // RichMahoganyBow
        [661] = new(12, WeaponClass.Ranged),  // PearlwoodBow
        [679] = new(36, WeaponClass.Ranged),  // TacticalShotgun
        [682] = new(40, WeaponClass.Ranged),  // Marrow
        [725] = new(39, WeaponClass.Ranged),  // IceBow
        [758] = new(60, WeaponClass.Ranged),  // GrenadeLauncher
        [759] = new(55, WeaponClass.Ranged),  // RocketLauncher
        [760] = new(80, WeaponClass.Ranged),  // ProximityMineLauncher
        [796] = new(19, WeaponClass.Ranged),  // TendonBow
        [800] = new(19, WeaponClass.Ranged),  // TheUndertaker
        [923] = new(8,  WeaponClass.Ranged),  // ShadewoodBow
        [964] = new(14, WeaponClass.Ranged),  // Boomstick
        [986] = new(27, WeaponClass.Ranged),  // Blowgun
        [1156] = new(40, WeaponClass.Ranged), // PiranhaGun
        [1187] = new(37, WeaponClass.Ranged), // PalladiumRepeater
        [1194] = new(40, WeaponClass.Ranged), // OrichalcumRepeater
        [1201] = new(43, WeaponClass.Ranged), // TitaniumRepeater
        [1229] = new(34, WeaponClass.Ranged), // ChlorophyteShotbow
        [1254] = new(200, WeaponClass.Ranged), // SniperRifle
        [1255] = new(50, WeaponClass.Ranged),  // VenusMagnum
        [1258] = new(45, WeaponClass.Ranged),  // Stynger
        [1265] = new(30, WeaponClass.Ranged),  // Uzi
        [1319] = new(10, WeaponClass.Ranged),  // SnowballCannon
        [1553] = new(85, WeaponClass.Ranged),  // SDMG
        [1782] = new(60, WeaponClass.Ranged),  // CandyCornRifle
        [1784] = new(85, WeaponClass.Ranged),  // JackOLanternLauncher
        [1835] = new(75, WeaponClass.Ranged),  // StakeLauncher
        [1870] = new(20, WeaponClass.Ranged),  // RedRyder
        [1910] = new(57, WeaponClass.Ranged),  // ElfMelter
        [1929] = new(38, WeaponClass.Ranged),  // ChainGun
        [1946] = new(67, WeaponClass.Ranged),  // SnowmanCannon
        [3007] = new(28, WeaponClass.Ranged),  // DartPistol
        [3008] = new(52, WeaponClass.Ranged),  // DartRifle
        [3019] = new(22, WeaponClass.Ranged),  // HellwingBow
        [3029] = new(38, WeaponClass.Ranged),  // DaedalusStormbow
        [3052] = new(47, WeaponClass.Ranged),  // ShadowFlameBow
        [3107] = new(85, WeaponClass.Ranged),  // NailGun
        [3210] = new(43, WeaponClass.Ranged),  // Toxikarp
        [3350] = new(12, WeaponClass.Ranged),  // PainterPaintballGun
        [3475] = new(50, WeaponClass.Ranged),  // VortexBeater
        [3540] = new(50, WeaponClass.Ranged),  // Phantasm
        [3546] = new(25, WeaponClass.Ranged),  // FireworksLauncher
        [3788] = new(24, WeaponClass.Ranged),  // OnyxBlaster
        [3821] = new(32, WeaponClass.Ranged),  // AleThrowingGlove
        [3854] = new(32, WeaponClass.Ranged),  // DD2PhoenixBow
        [3859] = new(38, WeaponClass.Ranged),  // DD2BetsyBow
        [3930] = new(50, WeaponClass.Ranged),  // Celeb2
        [4953] = new(50, WeaponClass.Ranged),  // FairyQueenRangedItem
        [5117] = new(20, WeaponClass.Ranged),  // PewMaticHorn
        [5282] = new(10, WeaponClass.Ranged),  // AshWoodBow
        [5460] = new(100, WeaponClass.Ranged), // DeadCellsBarrelLauncher
        // ---- 召唤（仆从伤害 ≠ 手持武器，仅权威数据，不参与武器校验）----
        [1157] = new(40, WeaponClass.Summon),  // PygmyStaff
        [1309] = new(8,  WeaponClass.Summon),  // SlimeStaff
        [1572] = new(100, WeaponClass.Summon), // StaffoftheFrostHydra
        [1802] = new(55, WeaponClass.Summon),  // RavenStaff
        [3249] = new(55, WeaponClass.Summon),  // DeadlySphereStaff
        [3474] = new(60, WeaponClass.Summon),  // StardustCellStaff
        [3531] = new(40, WeaponClass.Summon),  // StardustDragonStaff
        [3569] = new(100, WeaponClass.Summon), // MoonlordTurretStaff
        [3571] = new(130, WeaponClass.Summon), // RainbowCrystalStaff
        [3834] = new(17, WeaponClass.Summon),  // DD2ExplosiveTrapT3Popper
        [4269] = new(35, WeaponClass.Summon),  // SanguineStaff
        [4273] = new(11, WeaponClass.Summon),  // VampireFrogStaff
        [4281] = new(7,  WeaponClass.Summon),  // BabyBirdStaff
        [4607] = new(41, WeaponClass.Summon),  // StormTigerStaff
        [4758] = new(6,  WeaponClass.Summon),  // Smolstar
        [5005] = new(90, WeaponClass.Summon),  // EmpressBlade
        [5069] = new(8,  WeaponClass.Summon),  // FlinxStaff
        [5114] = new(6,  WeaponClass.Summon),  // AbigailsFlower
        [5119] = new(24, WeaponClass.Summon),  // HoundiusShootius
        [5456] = new(8,  WeaponClass.Summon),  // DeadCellsMushroomBoiSummonItem
        [5463] = new(33, WeaponClass.Summon),  // DeadCellsBarnacleSummonItem
        [5663] = new(11, WeaponClass.Summon),  // PalworldMinionCattiva
        [5664] = new(20, WeaponClass.Summon),  // PalworldMinionFoxsparks
        [6148] = new(22, WeaponClass.Summon),  // PalworldMinionTrustyCattiva
        [6149] = new(40, WeaponClass.Summon),  // PalworldMinionTrustyFoxsparks
        [6161] = new(5,  WeaponClass.Summon),  // ClayPotMinion
        [6164] = new(40, WeaponClass.Summon),  // ForbiddenMinion
        // ---- 阶段 E-5 补漏：缺失武器（NPC 掉落 / 1.4.5+ 新武器 / 信号枪等）----
        [930]  = new(2,  WeaponClass.Ranged),  // 信号枪 Flare Gun
        [3349] = new(20, WeaponClass.Melee),   // 染料商弯刀 Dye Trader's Scimitar
        [3351] = new(40, WeaponClass.Melee),   // 税收官末日棍 Tax Collector's Stick of Doom
        [3352] = new(14, WeaponClass.Melee),   // 发型师剪刀 Stylist's KilLaKill Scissors
        [4347] = new(42, WeaponClass.Magic),   // 灰色冲击枪 Zapinator (Gray)
        [4348] = new(100, WeaponClass.Magic),  // 橙色冲击枪 Zapinator (Orange)
        [4703] = new(14, WeaponClass.Ranged),  // 四管霰弹枪 Quad-Barrel Shotgun
        [5283] = new(9,  WeaponClass.Melee),   // 灰木锤 Ash Wood Hammer
        [5629] = new(5,  WeaponClass.Ranged),  // 橡实弹弓 Acorn Slingshot
        [6152] = new(8,  WeaponClass.Magic),   // 太阳花法杖 Daybloom Staff
        [6153] = new(11, WeaponClass.Magic),   // 冰川之牙 Glacier Fang
        [6154] = new(20, WeaponClass.Magic),   // 花瓣风暴 Petalstorm
        // ---- 阶段 F：投掷武器（消耗型，原版 1.4 起并入远程类；弹幕伤害 = 武器伤害，无弹药合并，可安全校验）----
        [42]  = new(10, WeaponClass.Ranged),   // 手里剑 Shuriken
        [154] = new(20, WeaponClass.Ranged),   // 骨头 Bone
        [161] = new(16, WeaponClass.Ranged),   // 尖刺球 Spiky Ball
        [168] = new(60, WeaponClass.Ranged),   // 手榴弹 Grenade
        [287] = new(14, WeaponClass.Ranged),   // 毒刀 Poisoned Knife
        [422] = new(20, WeaponClass.Ranged),   // 圣水 Holy Water
        [423] = new(20, WeaponClass.Ranged),   // 邪水 Unholy Water
        [1130] = new(12, WeaponClass.Ranged),  // 蜜蜂手榴弹 Beenade
        [1809] = new(13, WeaponClass.Ranged),  // 臭鸡蛋 Rotten Egg
        [1913] = new(14, WeaponClass.Ranged),  // 八角星 Star Anise
        [3094] = new(17, WeaponClass.Ranged),  // 标枪 Javelin
        [3116] = new(65, WeaponClass.Ranged),  // 弹力手榴弹 Bouncy Grenade
        [3197] = new(17, WeaponClass.Ranged),  // 霜冻匕首鱼 Frost Daggerfish
        [3378] = new(20, WeaponClass.Ranged),  // 骨标枪 Bone Javelin
        [3379] = new(14, WeaponClass.Ranged),  // 骨刀 Bone Dagger
        [3477] = new(20, WeaponClass.Ranged),  // 血水 Blood Water
        [3548] = new(30, WeaponClass.Ranged),  // 派对女孩手榴弹 Party Girl Grenade
        [5572] = new(8,  WeaponClass.Ranged),  // 泥球 Mud Ball
        [5577] = new(13, WeaponClass.Ranged),  // 漂亮镜子 Pretty Mirror
    };
}
